# Site
repository: FrancXPT/FrancXPT.github.io
favicon: images/favicon.ico
darkmode: false

# Personal info
name: Achraf Benbamoula
title: Software Developer
email: achrafbenbamoula@gmail.com
website: cv.francxpt.ga

# Social links
twitter_username: FrancXPT
github_username:  FrancXPT
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: achrafbamoula
linkedin_username: achraf-benbamoula-271407197
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/download.jfif
about_content: | # this will include new lines to allow paragraphs
  Hi, My name is Achraf. I am a Software Developper. I want to be at the bleeding edge of technology. 📚📈🔬, and I'm also a competitive programmer 🤩 🎈. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>.Net</mark> and <mark>Python</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Devloppment and Reading Documentations some of my other interests and hobbies are:
   - Mountain Biking
   - Gaming
   - [Pentesting](https://www.youtube.com/watch?v=rnmcRTnTNC8)
   - Eating

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
